name: secret-message

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up NPM authentication
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GPR_TOKEN }}" >> ~/.npmrc
      - name: npm install and test
        run: |
          npm ci
          npm test
        env:
          CI: true
      - name: Login via Azure CLI
        if: contains(github.ref, 'master')
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build
        if: contains(github.ref, 'master')
        run: |
          npm run build
      - name: Deploy to Azure Functions
        if: contains(github.ref, 'master')
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: dev-protocol
